export const data = [
    {
        "nodeId": "e06bfb2c-76e3-44f0-a1ad-c9ef9f360c40",
        "employeeId": "ba03fa6c-1337-4f8e-b85f-f7e6a4a6c54d",
        "registerId": "13291",
        "entryDate": 45733,
        "nodeName": "Amsterdamchoto",
        "nodeCode": "FM01",
        "employeeName": "a w s",
        "timeIn": 600,
        "timeOut": 780,
        "clockDeptId": 11,
        "clockDeptName": "Dep 2",
        "fromTime": 600,
        "toTime": 960,
        "totalTime": 360,
        "originalEntry": "Yes",
        "realizedDeptId": 11,
        "realizedDeptName": "Dep 2",
        "clockHourCodeAbbr": "N",
        "realizedHourCodeAbbr": "N",
        "sortTime": "600",
        "nodePath": "Amsterdamchoto",
        "sortCodePath": "2FM01"
    },
    {
        "nodeId": "e06bfb2c-76e3-44f0-a1ad-c9ef9f360c40",
        "employeeId": "ba03fa6c-1337-4f8e-b85f-f7e6a4a6c54d",
        "registerId": "13291",
        "entryDate": 45733,
        "nodeName": "Amsterdamchoto",
        "nodeCode": "FM01",
        "employeeName": "a w s",
        "timeIn": 840,
        "timeOut": 960,
        "clockDeptId": 11,
        "clockDeptName": "Dep 2",
        "fromTime": null,
        "toTime": null,
        "totalTime": null,
        "originalEntry": null,
        "realizedDeptId": null,
        "realizedDeptName": null,
        "clockHourCodeAbbr": "N",
        "realizedHourCodeAbbr": null,
        "sortTime": "840",
        "nodePath": "Amsterdamchoto",
        "sortCodePath": "2FM01"
    },
    {
        "nodeId": "e06bfb2c-76e3-44f0-a1ad-c9ef9f360c40",
        "employeeId": "ba03fa6c-1337-4f8e-b85f-f7e6a4a6c54d",
        "registerId": "13291",
        "entryDate": 45734,
        "nodeName": "Amsterdamchoto",
        "nodeCode": "FM01",
        "employeeName": "a w s",
        "timeIn": 540,
        "timeOut": 720,
        "clockDeptId": 11,
        "clockDeptName": "Dep 2",
        "fromTime": 540,
        "toTime": 720,
        "totalTime": 180,
        "originalEntry": "Yes",
        "realizedDeptId": 11,
        "realizedDeptName": "Dep 2",
        "clockHourCodeAbbr": "N",
        "realizedHourCodeAbbr": "N",
        "sortTime": "540",
        "nodePath": "Amsterdamchoto",
        "sortCodePath": "2FM01"
    },
    {
        "nodeId": "e06bfb2c-76e3-44f0-a1ad-c9ef9f360c40",
        "employeeId": "ba03fa6c-1337-4f8e-b85f-f7e6a4a6c54d",
        "registerId": "13291",
        "entryDate": 45734,
        "nodeName": "Amsterdamchoto",
        "nodeCode": "FM01",
        "employeeName": "a w s",
        "timeIn": 960,
        "timeOut": 1080,
        "clockDeptId": 11,
        "clockDeptName": "Dep 2",
        "fromTime": 960,
        "toTime": 1080,
        "totalTime": 120,
        "originalEntry": "Yes",
        "realizedDeptId": 11,
        "realizedDeptName": "Dep 2",
        "clockHourCodeAbbr": "N",
        "realizedHourCodeAbbr": "N",
        "sortTime": "960",
        "nodePath": "Amsterdamchoto",
        "sortCodePath": "2FM01"
    },
    {
        "nodeId": "e06bfb2c-76e3-44f0-a1ad-c9ef9f360c40",
        "employeeId": "ba03fa6c-1337-4f8e-b85f-f7e6a4a6c54d",
        "registerId": "13291",
        "entryDate": 45735,
        "nodeName": "Amsterdamchoto",
        "nodeCode": "FM01",
        "employeeName": "a w s",
        "timeIn": 540,
        "timeOut": 720,
        "clockDeptId": 11,
        "clockDeptName": "Dep 2",
        "fromTime": 540,
        "toTime": 720,
        "totalTime": 180,
        "originalEntry": "Yes",
        "realizedDeptId": 11,
        "realizedDeptName": "Dep 2",
        "clockHourCodeAbbr": "N",
        "realizedHourCodeAbbr": "N",
        "sortTime": "540",
        "nodePath": "Amsterdamchoto",
        "sortCodePath": "2FM01"
    },
    {
        "nodeId": "e06bfb2c-76e3-44f0-a1ad-c9ef9f360c40",
        "employeeId": "ba03fa6c-1337-4f8e-b85f-f7e6a4a6c54d",
        "registerId": "13291",
        "entryDate": 45736,
        "nodeName": "Amsterdamchoto",
        "nodeCode": "FM01",
        "employeeName": "a w s",
        "timeIn": 960,
        "timeOut": 1200,
        "clockDeptId": 11,
        "clockDeptName": "Dep 2",
        "fromTime": 960,
        "toTime": 1200,
        "totalTime": 240,
        "originalEntry": "Yes",
        "realizedDeptId": 11,
        "realizedDeptName": "Dep 2",
        "clockHourCodeAbbr": "N",
        "realizedHourCodeAbbr": "N",
        "sortTime": "960",
        "nodePath": "Amsterdamchoto",
        "sortCodePath": "2FM01"
    },
    {
        "nodeId": "e06bfb2c-76e3-44f0-a1ad-c9ef9f360c40",
        "employeeId": "ba03fa6c-1337-4f8e-b85f-f7e6a4a6c54d",
        "registerId": "13291",
        "entryDate": 45738,
        "nodeName": "Amsterdamchoto",
        "nodeCode": "FM01",
        "employeeName": "a w s",
        "timeIn": null,
        "timeOut": null,
        "clockDeptId": null,
        "clockDeptName": null,
        "fromTime": 540,
        "toTime": 720,
        "totalTime": 180,
        "originalEntry": "No",
        "realizedDeptId": 11,
        "realizedDeptName": "Dep 2",
        "clockHourCodeAbbr": null,
        "realizedHourCodeAbbr": "N",
        "sortTime": "540",
        "nodePath": "Amsterdamchoto",
        "sortCodePath": "2FM01"
    },
    {
        "nodeId": "e06bfb2c-76e3-44f0-a1ad-c9ef9f360c40",
        "employeeId": "ba03fa6c-1337-4f8e-b85f-f7e6a4a6c54d",
        "registerId": "13291",
        "entryDate": 45738,
        "nodeName": "Amsterdamchoto",
        "nodeCode": "FM01",
        "employeeName": "a w s",
        "timeIn": null,
        "timeOut": null,
        "clockDeptId": null,
        "clockDeptName": null,
        "fromTime": 840,
        "toTime": 1200,
        "totalTime": 360,
        "originalEntry": "No",
        "realizedDeptId": 11,
        "realizedDeptName": "Dep 2",
        "clockHourCodeAbbr": null,
        "realizedHourCodeAbbr": "N",
        "sortTime": "840",
        "nodePath": "Amsterdamchoto",
        "sortCodePath": "2FM01"
    }
]